T1146301 - The "Uncaught TypeError: arguments[1] is not a function" error occurs when a NamedTemplate that contains a widget with an HTML-encoded expression within Content (RazorBlock) is used by another widget Template